### ISSUE TITLE
He Tom! I bought your Gatsby course on Udemy but i have a question.

### ISSUE THREAD

**Issue by sjoerdvermeijden** [tomphill/wp-gatsby-js-theme-starter#1] opened 2020-07-09 14:10 UTC
When i query the posts from a custom post type i don't get " edges {  node ". Therefore i am only able to query the first post. Could you tell me what i'm doing wrong? Thanks!
![Schermafbeelding 2020-07-09 om 14 47 40](https://user-images.githubusercontent.com/13441035/87050514-a60dd600-c1fe-11ea-9c7d-734563cbeeea.png)
![Schermafbeelding 2020-07-09 om 15 41 42](https://user-images.githubusercontent.com/13441035/87050522-a8703000-c1fe-11ea-933d-4f6428ab5196.png)

**Comment by tomphill** [comment] 2020-07-15 04:07
Hey @sjoerdvermeijden - if you're still having this issue do you mind posting it in the Q&A on udemy? The issue isn't relevant to this repo so I'm gonna close it. Thanks!

**Closed as completed by tomphill** 2020-07-15 04:07 UTC
